AllCops:
  TargetRubyVersion: 2.3
  Exclude:
    - test/dummy/**/*
    - vendor/**/*

Layout/SpaceAroundOperators:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/ClassLength:
  Exclude:
    - test/**/*

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/LineLength:
  Enabled: false

Naming/AccessorMethodName:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/MixinUsage:
  Exclude:
    - test/dummy/bin/*

Style/NestedParenthesizedCalls:
  Enabled: false
