language: ruby
cache: bundler
rvm:
  - 2.4 # lowest version supported
  - 2.5
  - 2.6 # current version
  - ruby-head # next version
matrix:
  allow_failures:
  - rvm: ruby-head
bundler_args: -j4
script:
  - bundle exec standardrb --no-fix
  - bundle exec rails test
