language: ruby
cache: bundler
rvm:
  - 2.5 # lowest version supported
  - 2.6
  - 2.7
  - 3.0 # current version
  - ruby-head # next version
matrix:
  allow_failures:
  - rvm: ruby-head
bundler_args: -j4
script:
  - bundle exec standardrb --no-fix
  - bundle exec rails test
